# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cherry.ui'
#
# Created: Mon Jun 30 17:15:20 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainform(object):
    def setupUi(self, mainform):
        mainform.setObjectName(_fromUtf8("mainform"))
        mainform.resize(1146, 737)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("cherry.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainform.setWindowIcon(icon)
        self.Design_plate = QtGui.QLabel(mainform)
        self.Design_plate.setGeometry(QtCore.QRect(580, 70, 161, 17))
        self.Design_plate.setObjectName(_fromUtf8("Design_plate"))
        self.horizontalLayoutWidget = QtGui.QWidget(mainform)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 630, 123, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Type = QtGui.QLabel(self.horizontalLayoutWidget)
        self.Type.setObjectName(_fromUtf8("Type"))
        self.horizontalLayout.addWidget(self.Type)
        self.Type_choice = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.Type_choice.setObjectName(_fromUtf8("Type_choice"))
        self.Type_choice.addItem(_fromUtf8(""))
        self.Type_choice.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.Type_choice)
        self.upload = QtGui.QPushButton(mainform)
        self.upload.setGeometry(QtCore.QRect(350, 650, 114, 32))
        self.upload.setObjectName(_fromUtf8("upload"))
        self.sourcePlate = QtGui.QPushButton(mainform)
        self.sourcePlate.setGeometry(QtCore.QRect(510, 650, 114, 32))
        self.sourcePlate.setObjectName(_fromUtf8("sourcePlate"))
        self.Plate = QtGui.QTableWidget(mainform)
        self.Plate.setEnabled(True)
        self.Plate.setGeometry(QtCore.QRect(20, 110, 1101, 501))
        self.Plate.setCornerButtonEnabled(True)
        self.Plate.setRowCount(16)
        self.Plate.setColumnCount(22)
        self.Plate.setObjectName(_fromUtf8("Plate"))
        self.Plate.setColumnCount(22)
        self.Plate.setRowCount(16)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.Plate.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Plate.setItem(0, 0, item)
        self.Plate.horizontalHeader().setVisible(True)
        self.Plate.horizontalHeader().setCascadingSectionResizes(False)
        self.Plate.horizontalHeader().setDefaultSectionSize(80)
        self.Plate.horizontalHeader().setMinimumSectionSize(30)
        self.Plate.verticalHeader().setDefaultSectionSize(30)
        self.tabWidget = QtGui.QTabWidget(mainform)
        self.tabWidget.setGeometry(QtCore.QRect(20, 110, 1101, 501))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.tableview = QtGui.QTableView(self.tab1)
        self.tableview.setGeometry(QtCore.QRect(0, 0, 1101, 481))
        self.tableview.setObjectName(_fromUtf8("tableview"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.platetab2 = QtGui.QTableWidget(self.tab2)
        self.platetab2.setEnabled(True)
        self.platetab2.setGeometry(QtCore.QRect(0, 0, 1091, 471))
        self.platetab2.setCornerButtonEnabled(True)
        self.platetab2.setRowCount(16)
        self.platetab2.setColumnCount(21)
        self.platetab2.setObjectName(_fromUtf8("platetab2"))
        self.platetab2.setColumnCount(21)
        self.platetab2.setRowCount(16)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.platetab2.setVerticalHeaderItem(15, item)
        self.platetab2.horizontalHeader().setVisible(False)
        self.platetab2.horizontalHeader().setCascadingSectionResizes(False)
        self.platetab2.horizontalHeader().setDefaultSectionSize(80)
        self.platetab2.horizontalHeader().setMinimumSectionSize(30)
        self.platetab2.verticalHeader().setDefaultSectionSize(30)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.picking = QtGui.QPushButton(mainform)
        self.picking.setGeometry(QtCore.QRect(660, 650, 114, 32))
        self.picking.setObjectName(_fromUtf8("picking"))
        self.sourcePlate_2 = QtGui.QPushButton(mainform)
        self.sourcePlate_2.setGeometry(QtCore.QRect(810, 650, 114, 32))
        self.sourcePlate_2.setObjectName(_fromUtf8("sourcePlate_2"))

        self.retranslateUi(mainform)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainform)

    def retranslateUi(self, mainform):
        mainform.setWindowTitle(_translate("mainform", "Cherry Picking", None))
        self.Design_plate.setText(_translate("mainform", "Destination   Plate", None))
        self.Type.setText(_translate("mainform", "Type", None))
        self.Type_choice.setItemText(0, _translate("mainform", "Gene", None))
        self.Type_choice.setItemText(1, _translate("mainform", "Drug", None))
        self.upload.setText(_translate("mainform", "Upload", None))
        self.sourcePlate.setText(_translate("mainform", "Source", None))
        item = self.Plate.verticalHeaderItem(0)
        item.setText(_translate("mainform", "A", None))
        item = self.Plate.verticalHeaderItem(1)
        item.setText(_translate("mainform", "B", None))
        item = self.Plate.verticalHeaderItem(2)
        item.setText(_translate("mainform", "C", None))
        item = self.Plate.verticalHeaderItem(3)
        item.setText(_translate("mainform", "D", None))
        item = self.Plate.verticalHeaderItem(4)
        item.setText(_translate("mainform", "E", None))
        item = self.Plate.verticalHeaderItem(5)
        item.setText(_translate("mainform", "F", None))
        item = self.Plate.verticalHeaderItem(6)
        item.setText(_translate("mainform", "G", None))
        item = self.Plate.verticalHeaderItem(7)
        item.setText(_translate("mainform", "H", None))
        item = self.Plate.verticalHeaderItem(8)
        item.setText(_translate("mainform", "I", None))
        item = self.Plate.verticalHeaderItem(9)
        item.setText(_translate("mainform", "J", None))
        item = self.Plate.verticalHeaderItem(10)
        item.setText(_translate("mainform", "K", None))
        item = self.Plate.verticalHeaderItem(11)
        item.setText(_translate("mainform", "L", None))
        item = self.Plate.verticalHeaderItem(12)
        item.setText(_translate("mainform", "M", None))
        item = self.Plate.verticalHeaderItem(13)
        item.setText(_translate("mainform", "N", None))
        item = self.Plate.verticalHeaderItem(14)
        item.setText(_translate("mainform", "O", None))
        item = self.Plate.verticalHeaderItem(15)
        item.setText(_translate("mainform", "P", None))
        item = self.Plate.horizontalHeaderItem(0)
        item.setText(_translate("mainform", "1", None))
        __sortingEnabled = self.Plate.isSortingEnabled()
        self.Plate.setSortingEnabled(False)
        self.Plate.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("mainform", "Tab 1", None))
        item = self.platetab2.verticalHeaderItem(0)
        item.setText(_translate("mainform", "A", None))
        item = self.platetab2.verticalHeaderItem(1)
        item.setText(_translate("mainform", "B", None))
        item = self.platetab2.verticalHeaderItem(2)
        item.setText(_translate("mainform", "C", None))
        item = self.platetab2.verticalHeaderItem(3)
        item.setText(_translate("mainform", "D", None))
        item = self.platetab2.verticalHeaderItem(4)
        item.setText(_translate("mainform", "E", None))
        item = self.platetab2.verticalHeaderItem(5)
        item.setText(_translate("mainform", "F", None))
        item = self.platetab2.verticalHeaderItem(6)
        item.setText(_translate("mainform", "G", None))
        item = self.platetab2.verticalHeaderItem(7)
        item.setText(_translate("mainform", "H", None))
        item = self.platetab2.verticalHeaderItem(8)
        item.setText(_translate("mainform", "I", None))
        item = self.platetab2.verticalHeaderItem(9)
        item.setText(_translate("mainform", "J", None))
        item = self.platetab2.verticalHeaderItem(10)
        item.setText(_translate("mainform", "K", None))
        item = self.platetab2.verticalHeaderItem(11)
        item.setText(_translate("mainform", "L", None))
        item = self.platetab2.verticalHeaderItem(12)
        item.setText(_translate("mainform", "M", None))
        item = self.platetab2.verticalHeaderItem(13)
        item.setText(_translate("mainform", "N", None))
        item = self.platetab2.verticalHeaderItem(14)
        item.setText(_translate("mainform", "O", None))
        item = self.platetab2.verticalHeaderItem(15)
        item.setText(_translate("mainform", "P", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("mainform", "Tab 2", None))
        self.picking.setText(_translate("mainform", "Picking", None))
        self.sourcePlate_2.setText(_translate("mainform", "Source2", None))

